### ISSUE TITLE
Undefined symbols for architecture: on Xcode 8.0/Sierra 10.12

### ISSUE THREAD

**Issue by CenoX** [google/google-toolbox-for-mac#128]
Undefined symbols for architecture armv7:
  "_GTMMethodCheckMethodChecker", referenced from:
      +[NSDictionary(GTMNSDictionaryURLArgumentsAdditions) xxGTMMethodCheckMethodNSString32] in GTMNSDictionary+URLArguments.o
      +[NSDictionary(GTMNSDictionaryURLArgumentsAdditions) xxGTMMethodCheckMethodNSString33] in GTMNSDictionary+URLArguments.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

<img width="243" alt="2016-10-27 1 42 17" src="https://cloud.githubusercontent.com/assets/5639358/19754741/357407ca-9c4b-11e6-9bd2-8f80f223edc6.png">

via cocoapods library

build was for iOS Device in "DEBUG"

**Comment by thomasvl** [comment]
What version of GTM are you using?  Looks like it could be an older release, can you try updating to the 2.1.0 release and see if it resolves things?

**Comment by lorcanotoole** [comment]
I'm having the same issue with 2.1.0

**Comment by thomasvl** [comment]
Can you post a example showing how to recreate this?  It almost sounds like you have some code compiled with the old version of `GTMMethodCheck`, as the [current version](https://github.com/google/google-toolbox-for-mac/blob/v2.1.0/DebugUtils/GTMMethodCheck.h) no longer creates class methods like that.

**Comment by CenoX** [comment]
here is the [sample proj](https://github.com/CenoX/googleGTMCheckerSample)

just build, then you can see the error.

GTM added by pod 'Google/SignIn'

and pod installed
Downloading dependencies
Installing FirebaseAnalytics (3.5.1)
Installing FirebaseCore (3.4.4)
Installing FirebaseInstanceID (1.0.8)
Installing GTMOAuth2 (1.1.4)
Installing GTMSessionFetcher (1.1.7)
Installing Google (3.0.3)
Installing GoogleAppUtilities (1.1.2)
Installing GoogleInterchangeUtilities (1.2.2)
Installing GoogleSignIn (4.0.1)
Installing GoogleSymbolUtilities (1.1.2)
Installing GoogleToolboxForMac (2.1.0)
Generating Pods project
Integrating client project

**Comment by thomasvl** [comment]
@perotinus I'm guessing the problem here is those other pods include prebuilt binaries so they have to use GoogleToolboxForMac 2.0.1 so the code matches what they were compiled against?  I had pumped the number to 2.1 to hopefully avoid having it picked up by things that weren't ready, but I guess a bunch of those use `>=` instead of `~>`?

**Comment by CenoX** [comment]
Here is 'Google/SignIn' depends on:

GoogleAppUtilities	~> 1.1
GTMOAuth2	~> 1.0
GTMSessionFetcher/Core	~> 1.1
GoogleToolboxForMac/NSDictionary+URLArguments

**Comment by perotinus** [comment]
Hmm. This doesn't look like an issue with the Daylight recompiled pods: I don't see any GSDK prefixes there that would indicate that the recompiled pods were causing an issue here.

@CenoX I was unable to replicate this with the demo project and repro steps you provided: I built the project after running `pod install` and it worked fine for me. Perhaps you could try deleting the Pods directory and Podfile.lock and rerunning `pod install`?

**Comment by CenoX** [comment]
As you said, I cleaned my build data (also Podfile.lock and re-install pod), GTM built successfully.

well, then it is not GTM's bug but another library's source code contains that(_GTMMethodCheckMethodChecker) so build get errors?

**Comment by perotinus** [comment]
That would be my guess. It looks like the errors you linked above were from GTM depending on itself, which seems like an odd state to be in. Is it still not building for you? Have you tried deleting derived data? It seems like the GTM pod got in an inconsistent state, and like you need to remove all the cached data and try again.

If you can replicate it, can you provide more details so that we can try to replicate it on our end?

**Comment by CenoX** [comment]
Got it. Because of 'GooglePlayGames' pods.

I committed changes to [previous sample proj](https://github.com/CenoX/googleGTMCheckerSample)

and you can replicate the errors.

**Comment by perotinus** [comment]
Thanks! I don't see any changes to that repo, though. Can you push your changes?

**Comment by CenoX** [comment]
remote: Resolving deltas: 100% (76/76), completed with 19 local objects.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: d38b87a94f01f386442dbde035774d77
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Pods/GooglePlayGames/gpg-cpp-sdk/ios/gpg.framework/Versions/A/gpg is 126.91 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/CenoX/googleGTMCheckerSample.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/CenoX/googleGTMCheckerSample.git'

Size limitaion..

just add **pod 'GooglePlayGames'** into the Podfile and install
then you can see the error

**Comment by perotinus** [comment]
Got it. It looks like this has something to do with the GooglePlayGames pod, and probably the GooglePlusOpenSource pod that it depends on. My guess is that the GooglePlusOpenSource pod has a precompiled version of GTM that doesn't have its symbols renamed, and the linker gets confused when it sees that in the set of libraries that it should use when trying to link the GTM pod.

I'm not sure that there's much that we can do about this on the GTM end. It appears to work if you force GoogleToolboxForMac to version 2.0.0, but I don't think that's a great solution, because it forces a number of other pods to downgrade as well. You may want to reach out to the owners of the GooglePlayGames pod and see if they have a workaround.

**Comment by CenoX** [comment]
Okay, then this is NOT GTM's problem right?
I'll ask to GooglePlayGames pod's owner.

**Comment by CenoX** [comment]
Do you know where I can report this problem?

**Comment by perotinus** [comment]
I think your best bet is to check the team's support page at https://developers.google.com/games/services/ios/support and see if you can report the issue there. It looks like they recommend opening a Stack Overflow post, which they should see if you tag it appropriately.

**Comment by CenoX** [comment]
thanks
