### ISSUE TITLE
Crash when set a value in UserDefaults

### ISSUE THREAD

**Issue by MamuninaNV** [google/google-toolbox-for-mac#238]
We use two libraries which are using UserDefaults.standard (your's and Armchair).
Because of some intersection in how these libraries operate with UserDefaults, we get a crash in our application.
As a temporary solution we made a fork of smaller and simpler library - Armchair and use non-standard UserDefaults.
For example:

```let userDefaults = UserDefaults(suiteName: "com.github.CompanyName.VendorName")!```

Maybe you could do something similar or maybe you have your own decision about that.

Helpful links:

Our problem solution
https://github.com/roxiemobile-forks/Armchair/commit/cb64462a38a1eb6dbcb63fc4991ce2da1d342b1a

NSUserDefaults KVO conflict with Adobe DMP
https://github.com/Adobe-Marketing-Cloud/mobile-services/issues/284

**Comment by thomasvl** [comment]
Can you provide more details on what in this library is using defaults and causing the conflict?  As reported, there really isn't anything that can be investigated here.

**Comment by fumoboy007** [comment]
The root cause of the crash is an overrelease of `GTMLogLevelFilter` due to a KVO-related race condition. (Reported internally as b/183973006.)

# Bug

`GTMLogLevelFilter` uses KVO to observe the `GTMVerboseLogging` user defaults key. It [adds itself as an observer](https://github.com/google/google-toolbox-for-mac/blob/39db54d1af47140b8ea89a1b42e9588acb03aecf/Foundation/GTMLogger.m#L515-L518) in `init` and [removes itself](https://github.com/google/google-toolbox-for-mac/blob/39db54d1af47140b8ea89a1b42e9588acb03aecf/Foundation/GTMLogger.m#L527) in `dealloc`. However, as explained in [inessential: Observers and Thread Safety](https://inessential.com/2013/12/20/observers_and_thread_safety), this pattern is subject to a race condition:

1. [Thread A] A `GTMLogLevelFilter` instance is initialized. It starts to observe `NSUserDefaults`.
2. [Thread A] The instance is released and is starting to be deallocated. Its `dealloc` has not been executed yet, so the instance is still registered as an observer.
3. [Thread B] A user defaults value is modified. `NSUserDefaults` prepares to notify observers by retaining its observers. The `GTMLogLevelFilter` instance is successfully “retained” even though it is being deallocated.
4. [Thread A] The instance finishes deallocation.
5. [Thread B] `NSUserDefaults` finishes notifying observers by releasing the observers it previously retained. This causes a crash because the `GTMLogLevelFilter` instance has already been deallocated.

The race condition can be verified by running [this sample project](https://github.com/google/google-toolbox-for-mac/files/6225200/GTMLogLevelFilterRaceCondition.zip).

# Impact

It is a common occurrence for a `GTMLogLevelFilter` to be initialized and subsequently deallocated because of this common pattern: the app calls `+[GTMLogger standardLogger]`, which creates a `GTMLogLevelFilter` to be used as the default filter, and then calls `-[GTMLogger setFilter:]` to override the default filter.

Reported crashes:
- https://github.com/Adobe-Marketing-Cloud/mobile-services/issues/264
- https://github.com/Adobe-Marketing-Cloud/mobile-services/issues/284
- https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/147
- Google Internal: b/174670711
- Google Internal: b/183448095

**Comment by williamisaac951** [comment]
Help me fix Google

**Comment by jiemi** [comment]
Hi，Please，When will the new version of this fix be released?

**Comment by thomasvl** [comment]
Thanks for the nudge, new version released.

**Comment by jiemi** [comment]
> Thanks for the nudge, new version released.

Thanks for the update
