### ISSUE TITLE
Unreleased Resource

### ISSUE THREAD

**Issue by gopalchinnadurai** [google/google-toolbox-for-mac#252]
We have used GoogleToolboxForMac 2.2.1 as per our need. Some VAPT points are mentioned in below picture. Kindly help us asap.

**Issue Summary**

The function fileHandleForLoggingAtPath:mode:() in GTMLogger.m sometimes fails to release a system resource allocated by open() on line 340.The program can potentially fail to release a system resource.

**Issue Screenshot**

<img width="540" alt="Screenshot 2019-12-23 at 6 20 03 PM" src="https://user-images.githubusercontent.com/55129685/71358961-dcf90300-25b0-11ea-9cf5-6373fbd4c5ee.png">

**Comment by thomasvl** [comment]
If you look at the code in question:

https://github.com/google/google-toolbox-for-mac/blob/master/Foundation/GTMLogger.m#L340-L344

It does use `open`, but when `open` returns `-1`, then there was an error, and the routine exits; otherwise, it creates a new `NSFileHandle` passing off the ownership of the file descriptor with `closeOnDealloc:YES`.  So the System library will close the descriptor when the `NSFileHandle` is released.

So based on the information in this report, there does not appear to be any way this ends up being leaked.
