### ISSUE TITLE
`GoogleToolboxForMac` 4.2.1 is not compatible with `GoogleMLKit` 5.0.0

### ISSUE THREAD

**Issue by hung-nguyen-90** [google/google-toolbox-for-mac#448]
I'm not sure if this is an issue with `GoogleToolboxForMac`, but since I can't find the repository for `GoogleMLKit`, so I'm creating an issue here.

Currently, we need to update `GoogleToolboxForMac` to version 4.2 for the Privacy manifest file. Our app does not directly use `GoogleToolboxForMac`; it is a dependency of `GoogleMLKit`. I have updated `GoogleMLKit/FaceDetection` to 5.0.0, but `GoogleToolboxForMac` does not automatically update with it. I have tried `pod update GoogleToolboxForMac`, but it doesn't work.

I created a TEST project to try with the `Podfile` as below: 
<img width="500" alt="Screenshot 2024-03-26 at 16 50 16" src="https://github.com/google/google-toolbox-for-mac/assets/5350857/c4ff001e-ef11-427c-9006-7df39e014880">

After running pod install, it displayed an error like this:
<img width="600" alt="Screenshot 2024-03-26 at 16 50 34" src="https://github.com/google/google-toolbox-for-mac/assets/5350857/9c2c62dc-7698-4c26-8e8c-0d4ae871558b">

Could you help me resolve this issue? Thank you very much!

**Comment by thomasvl** [comment]
From the screen shots, the problem is in the GoogleMLKit -> MLKitCommon chain, they have dependencies that are set up not to allow going past GTM 2.x, so MLKitCommon is the ones that have to update to allow newer versions.

https://github.com/CocoaPods/Specs/blob/master/Specs/b/e/b/GoogleMLKit/3.2.0/GoogleMLKit.podspec.json#L34C10-L36

https://github.com/CocoaPods/Specs/blob/master/Specs/c/c/6/MLKitCommon/8.0.0/MLKitCommon.podspec.json#L10-L18

**Comment by hung-nguyen-90** [comment]
I found some useful information here: https://github.com/googlesamples/mlkit/issues/795#issuecomment-2018175856 
Let's wait for GoogleMLKit to release a new version. Thank you!
